steps:
  - label: ":construction: Build the documentation"
    key: build-docs
    env:
      GITHUB_SSH_KEY: ${GITHUB_SSH_KEY?}
      JULIA_PKG_USE_CLI_GIT: true
    plugins:
      - staticfloat/ssh-agent:
          keyvars:
            - "GITHUB_SSH_KEY"
      # Install Julia v1.x to run Sandbox.jl
      - JuliaCI/julia#v1:
          version: 1
      - staticfloat/sandbox#v1:
          rootfs_url: "https://github.com/JuliaCI/rootfs-images/releases/download/v4.4/agent_linux.x86_64.tar.gz"
          rootfs_treehash: "81e406f08d77041c61c7f8731e3d016973e1fdd8"
          workspaces:
            # Include `/cache` so that `julia` install can properly cache its Julia downloads
            - "/cache:/cache"
            # Include `~/.ssh` so that we get the pre-filled `known_hosts` file
            - "${HOME}/.ssh:/root/.ssh"
      # Run tests
    commands: |
      export DOCUMENTER_KEY=$${GITHUB_SSH_KEY}
      echo "+++ Building docs..."
      julia --project=docs -e '
        using Pkg
        Pkg.setprotocol!(protocol="ssh")
        Pkg.Registry.add(Pkg.RegistrySpec(url = "git@github.com:JuliaComputing/JuliaSimRegistry", uuid = "309a7822-a73e-4490-9504-7d1983f27685"))
        Pkg.develop(PackageSpec(path = pwd()))
        Pkg.instantiate()'

      julia --project=docs docs/make.jl

    if: build.message !~ /\[skip docs build\]/
    timeout_in_minutes: 120

    agents:
      sandbox.jl: true